name: Docker Image CI

on: 
  push:
    paths:
      - 'backend/**'

jobs: 
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push the backend image
        run: |
          docker login --username pahulgogna --password ${{secrets.GH_PAT}} ghcr.io

          docker build ./backend --tag ghcr.io/pahulgogna/shrtly-backend:latest

          docker push ghcr.io/pahulgogna/shrtly-backend:latest

  deploy:
      permissions:
        contents: none
      runs-on: ubuntu-latest
      needs: build_and_publish
      environment:
        name: 'Development'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      steps:
        - name: Lowercase the repo name and username
          run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
        - name: Deploy to Azure Web App
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2
          with:
            app-name: ${{ secrets.AZURE_APP_NAME }}
            publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
            images: 'ghcr.io/pahulgogna/shrtly-backend:latest'