name: Docker Image CI

on: 
  push:
    paths:
      - 'backend/**'

jobs: 
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push the backend image
        run: |
          docker login --username pahulgogna --password ${{secrets.GH_PAT}} ghcr.io

          docker build ./backend --tag ghcr.io/pahulgogna/shrtly-backend:latest

          docker push ghcr.io/pahulgogna/shrtly-backend:latest

